### ISSUE TITLE
Conflict between gcc-avr and gcc-pru

### ISSUE THREAD

**Issue by carlosm180** [monoxide13/CRAMPS-and-Klipper#1]
Using Debian 10.3 IoT image on my Beaglebone black, running "install-beaglebone.sh" there is a conflict because both gcc-avr and bcc-pru try to override '/usr/lib/libcc1.la'.
I notice "klipper_beaglebone.patch" remove and rewrite the same line :
sudo cp "${SRCDIR}/scripts/klipper-pru-start.sh" /etc/init.d/klipper_pru
...perhaps there is to change patch file?
thanks
Carlo

**Comment by carlosm180** [comment]
I install 10.13 and I comment all the lines in "step 2" of install-debian.sh file (it was referred to python2, now there is python3 in Debian10.13): I don't know if it is correct, but now I haven't any conflict between pru and avr.
Unfortunatly, klipper doesn't create /tmp/printer

**Comment by monoxide13** [comment]
Yeah, klipper has been updated to Python3. I haven't gone back and updated this project since I'm still running a really old klipper version. It's been working fine for me so I don't have a reason to change.
