### ISSUE TITLE
Not a Issue, a plea!

### ISSUE THREAD

**Issue by carlosm180** [monoxide13/CRAMPS-and-Klipper#2]
I have spent too much time on my CRAMPS, without appreciable results. But, since the Beaglebone is the same and the CRAMPS is the same, I ask you: do you have an image of your working system to share? It's a cheeky request, I know, but I'm out of ideas and desperate!

**Comment by monoxide13** [comment]
All you should need is the printer.cfg file in the repo to configure the BB from CRAMPS. What is the actual issue you are having?

**Comment by carlosm180** [comment]
I have various problems, especially related to the fact that, with updates, incompatibilities arise between libraries and also with Python commands. Also, to make the PRU work, I followed various guides because it often wasn't activated... but where I solve one issue, I mess up something else! I think the problems depend on the Linux system, not on Klipper... for this reason I asked you if there is an image of a worked system....my problems start before klipper. Thanks for answered me and have a nice day!
